import React from "react";

import Head from "next/head";
import { useForm, SubmitHandler } from "react-hook-form";
import Link from "next/link";

type Inputs = {
  firstName: string;
  lastName: string;
};

export default function Basic() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<Inputs>();

  const [data, setData] = React.useState<Inputs>();

  const onSubmit: SubmitHandler<Inputs> = (data) => setData(data);

  return (
    <div>
      <Head>
        <title>Basic Form</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gray-900 w-screen min-h-screen pt-20 overflow-hidden'>
        <div className='w-11/12 lg:w-1/2 xl:w-1/3 mx-auto text-center'>
          <h1 className='text-5xl font-bold font-mono'>Basic Form</h1>
          <div className='mt-12 rounded-lg border h-fit p-8'>
            <form onSubmit={handleSubmit(onSubmit)}>
              <div className='mt-4 flex flex-col justify-start relative'>
                <label className='text-left font-mono' htmlFor='firstName'>
                  First Name
                </label>
                <input
                  className='mt-1 shadow appearance-none bg-transparent border rounded w-full py-3 px-3 text-gray-200 leading-tight'
                  type='text'
                  id='firstName'
                  {...register("firstName", {
                    required: {
                      value: true,
                      message: "This field is required",
                    },
                  })}
                />
                {errors.firstName && (
                  <p className='absolute -bottom-6 text-left font-medium text-red-700'>
                    {errors.firstName.message}
                  </p>
                )}
              </div>
              <div className='mt-12 flex flex-col justify-start relative'>
                <label className='text-left font-mono' htmlFor='lastName'>
                  Last Name
                </label>
                <input
                  className='mt-1 shadow appearance-none bg-transparent border rounded w-full py-3 px-3 text-gray-200 leading-tight'
                  type='text'
                  id='lastName'
                  {...register("lastName", {
                    required: {
                      value: true,
                      message: "This field is required",
                    },
                  })}
                />
                {errors.lastName && (
                  <p className='absolute -bottom-6 text-left font-medium text-red-700'>
                    {errors.lastName.message}
                  </p>
                )}
              </div>
              <button className='w-fit mx-auto rounded-md border border-white py-2 px-4 mt-12 hover:bg-white hover:text-gray-700'>
                Submit
              </button>
            </form>
          </div>
          <div className='mt-2 full mx-auto h-fit'>
            <pre>{JSON.stringify(data, null, 2)}</pre>
          </div>
          <Link
            href={"/"}
            className='nav-back w-fit py-3 px-8 font-mono text-xl'
          >
            Back
          </Link>
        </div>
      </main>
    </div>
  );
}
