import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-gray-900 w-screen h-screen flex flex-col gap-12 items-center justify-center'>
        <h1 className='text-5xl font-bold font-mono'>React Hook Form</h1>
        <div className='flex gap-12 text-3xl'>
          <Link className='nav' href='/basic'>
            Basic
          </Link>
          <Link className='nav' href='/about'>
            About Us
          </Link>
          <Link className='nav' href='/blog/hello-world'>
            Blog Post
          </Link>
        </div>
      </main>
    </div>
  );
}
